// Simple in-memory blog data. Replace later with a CMS or Markdown.

export const posts = [
  {
    slug: "curriculo-estagio-2025-modelos-ats-palavras-chave",
    title: "Currículo para estágio 2025: modelos, ATS e palavras‑chave",
    excerpt: "Currículo claro, direto e compatível com ATS aumenta convites para entrevista em 2025.",
    cover: "/curriculo-2025.png",
    tag: "Currículo",
    tags: ["Currículo", "ATS", "Palavras‑chave"],
    author: { name: "Equipe Estágio AI" },
    date: "2025-08-20",
    readingTimeMinutes: 9,
    sections: [
      { id: "introducao", heading: "Introdução", body: ["O primeiro contato do recrutador é o currículo: claro, direto e alinhado à vaga. Em 2025, conteúdo legível por ATS e personalizado por área aumenta convites para entrevista."]},
      { id: "por-que-importa", heading: "Por que importa", list: ["ATS filtra por termos e formato legível.", "Escaneabilidade em segundos decide avanço no processo."]},
      { id: "estrutura", heading: "Estrutura recomendada", list: ["Cabeçalho: nome, telefone, e-mail profissional, cidade/UF, LinkedIn.", "Objetivo: função/área + valor que entrega + curso/período.", "Formação: curso, instituição, início–previsão, tópicos relevantes.", "Experiência: estágios, projetos, voluntariado, monitoria, freelas (3–5 bullets com resultados).", "Habilidades: técnicas e comportamentais alinhadas à vaga.", "Extras: certificações, idiomas, eventos, portfólio."]},
      { id: "ats", heading: "Como agradar o ATS", list: ["Use palavras‑chave exatas da vaga.", "Evite imagens/colunas/ícones; prefira PDF simples com texto.", "Títulos padrão: “Experiência”, “Formação”, “Habilidades”."]},
      { id: "keywords", heading: "Palavras‑chave por área", list: ["Administração: Excel, relatórios, indicadores, ERP, organização.", "Marketing: social media, SEO, tráfego pago, copy, analytics.", "TI: JavaScript, Python, Git, SQL, APIs, testes.", "Direito: peças, pesquisa jurisprudencial, PJe, prazos.", "Engenharia: AutoCAD, desenho técnico, Lean, Excel avançado."]},
      { id: "erros", heading: "Erros comuns", list: ["Objetivo genérico.", "Blocos longos sem números.", "Dados sensíveis (CPF, estado civil)."]},
      { id: "checklist", heading: "Checklist final", list: ["1 página, fonte 11–12, bullets com métricas, termos da vaga, LinkedIn/portfólio."]},
      { id: "cta", heading: "", cta: { label: "Baixar modelo + 200 palavras‑chave", href: "/em-construcao" }},
    ],
  },
  {
    slug: "entrevista-estagio-20-perguntas-boas-respostas",
    title: "Entrevista de estágio: 20 perguntas e boas respostas",
    excerpt: "Use STAR, mini‑roteiros e perguntas finais para performar melhor nas entrevistas.",
    cover: "/perguntas-entrevistador.png",
    tag: "Entrevista",
    tags: ["Entrevista", "Perguntas e respostas", "STAR"],
    author: { name: "Equipe Estágio AI" },
    date: "2025-08-22",
    readingTimeMinutes: 10,
    sections: [
      { id: "introducao", heading: "Introdução", body: ["A entrevista valida fit, comunicação e motivação. Preparação objetiva reduz ansiedade e melhora desempenho."]},
      { id: "star", heading: "Como responder (STAR)", list: ["Situação, Tarefa, Ação, Resultado.", "Use projetos/monitorias/voluntariados como casos.", "Conecte respostas à vaga e ao time."]},
      { id: "perguntas", heading: "Perguntas frequentes (resumos)", list: ["Fale sobre si: 60–90s unindo curso, projetos e objetivo.", "Por que esta empresa: missão, produtos, cultura, aprendizados.", "Pontos fortes: 1–2 com exemplo concreto.", "Ponto a desenvolver: evolução e plano de melhoria.", "Conflito em equipe: mediação, comunicação, resultado.", "Erro e aprendizado: responsabilidade, correção, prevenção.", "Organização do tempo: método e impacto.", "Disponibilidade: horários, formato, início.", "Pretensão: políticas da empresa e foco em aprendizado.", "Perguntas ao final: ver roteiro dedicado."]},
      { id: "mini", heading: "Mini-roteiros por área", list: ["Marketing: crescimento de engajamento ou teste A/B.", "TI: bug crítico, debug e PR revisado.", "Administração: ganho de eficiência em processos.", "Direito: pesquisa que encurtou prazos e embasou decisão."]},
      { id: "checklist", heading: "Checklist", list: ["3 cases STAR prontos, 3 perguntas finais, apresentação de 60s."]},
      { id: "cta", heading: "", cta: { label: "Acessar simulador de entrevista", href: "/em-construcao" }},
    ],
  },
  {
    slug: "como-conseguir-estagio-sem-experiencia",
    title: "Como conseguir estágio sem experiência",
    excerpt: "Projetos, rede e certificações curtas são alavancas para conquistar a primeira vaga.",
    cover: "/estagioai-background.png",
    tag: "Carreira",
    tags: ["Sem experiência", "LinkedIn", "Networking"],
    author: { name: "Equipe Estágio AI" },
    date: "2025-08-25",
    readingTimeMinutes: 7,
    sections: [
      { id: "introducao", heading: "Introdução", body: ["Sem experiência formal, o potencial aparece em projetos, eventos e rede, suficientes para conquistar a primeira vaga."]},
      { id: "alavancas", heading: "Alavancas práticas", list: ["Projetos rápidos: estudos de caso, desafios públicos, Git/portfólio.", "Rede: eventos, meetups, grupos de curso; pedir indicações com contexto.", "Plataformas: portais de estágio e LinkedIn Jobs; alertas por palavra‑chave.", "Certificações curtas: cursos gratuitos com projeto final.", "Voluntariado e monitoria: impacto mensurável."]},
      { id: "plano", heading: "Plano 30–60–90 dias", list: ["0–30: currículo/LinkedIn, 2 projetos, 10 candidaturas direcionadas.", "31–60: 2 eventos, 2 certificações, 10 conexões qualificadas.", "61–90: 3 entrevistas simuladas, 15 candidaturas personalizadas."]},
      { id: "templates", heading: "Templates rápidos", list: ["Networking: contexto, objetivo, pedido específico, agradecimento.", "Pós‑processo: agradecimento, reforço de fit, disponibilidade."]},
      { id: "kpis", heading: "KPIs pessoais", list: ["Candidaturas/semana, convites/candidatura, taxa de entrevista."]},
      { id: "cta", heading: "", cta: { label: "Baixar playbook 90 dias", href: "/em-construcao" }},
    ],
  },
  {
    slug: "habilidades-mais-valorizadas-estagiarios-2025",
    title: "Habilidades mais valorizadas em estagiários (2025)",
    excerpt: "Comportamentais e técnicas que mostram prontidão e aprendizado acelerado.",
    cover: "/logo-web copy.png",
    tag: "Habilidades",
    tags: ["Comunicação", "Colaboração", "Dados"],
    author: { name: "Equipe Estágio AI" },
    date: "2025-08-27",
    readingTimeMinutes: 8,
    sections: [
      { id: "introducao", heading: "Introdução", body: ["Habilidades técnicas e comportamentais mostram prontidão e aprendizado acelerado. Em 2025, adaptabilidade e dados ganham destaque."]},
      { id: "comportamentais", heading: "Comportamentais", list: ["Comunicação clara.", "Colaboração e abertura a feedback.", "Organização e autonomia responsável.", "Resolução de problemas.", "Adaptabilidade e curiosidade."]},
      { id: "tecnicas", heading: "Técnicas por área", list: ["Marketing: analytics, SEO básico, Canva, copy.", "TI: Git, APIs, SQL, testes, cloud introdutório.", "Administração: Excel/Sheets, dashboards, finanças básicas.", "Direito: pesquisa jurisprudencial, PJe, formatação.", "Engenharia: leitura de projeto, CAD, planilhas técnicas."]},
      { id: "provar", heading: "Como provar", list: ["Projetos com métricas.", "Certificações com laboratório/projeto.", "Casos STAR em entrevista."]},
      { id: "cta", heading: "", cta: { label: "Autoavaliação e plano de estudo", href: "/em-construcao" }},
    ],
  },
  {
    slug: "objetivo-profissional-estagio-como-escrever-15-exemplos",
    title: "Objetivo profissional para estágio: como escrever (+15 exemplos)",
    excerpt: "Fórmula simples e exemplos por área para um objetivo direto e eficaz.",
    cover: "/react.svg",
    tag: "Currículo",
    tags: ["Objetivo profissional", "Exemplos"],
    author: { name: "Equipe Estágio AI" },
    date: "2025-08-29",
    readingTimeMinutes: 6,
    sections: [
      { id: "introducao", heading: "Introdução", body: ["O objetivo orienta o foco do estágio, alinhando área, contribuição e aprendizado."]},
      { id: "formula", heading: "Fórmula", body: ["[Área/função] + [como contribuir] + [curso/período]."]},
      { id: "exemplos", heading: "Exemplos por área (15)", list: [
        "Administração: Controladoria para apoiar conciliações e indicadores, 4º período.",
        "Administração: Planejamento comercial com análise de sell‑out, 6º período.",
        "Administração: Processos e melhoria contínua (5S/Kaizen), 5º período.",
        "Marketing: Social Media com calendário e métricas, 3º semestre.",
        "Marketing: Conteúdo SEO e análise de tráfego orgânico, 4º semestre.",
        "Marketing: Performance (Meta/Google) com testes A/B, 5º semestre.",
        "TI: Front‑end (React) para manutenção de componentes e testes, 2º ano.",
        "TI: Back‑end (Node/SQL) para APIs e integrações, 3º ano.",
        "TI: QA para automação de testes e qualidade, 2º ano.",
        "Direito: Cível para pesquisa jurisprudencial e minutas, 6º período.",
        "Direito: Trabalhista para controle de prazos e audiências, 7º período.",
        "Direito: Tributário para pesquisas e peças iniciais, 5º período.",
        "Engenharia: Projetos para desenho técnico e orçamentos, 7º semestre.",
        "Engenharia: Processos (Lean) e tempos & métodos, 6º semestre.",
        "Engenharia: Qualidade (ISO/CEP) com relatórios, 8º semestre.",
      ]},
      { id: "erros", heading: "Erros a evitar", list: ["Frases genéricas.", "Lista de desejos sem valor para a empresa.", "Texto longo; mantenha 1–2 linhas."]},
      { id: "cta", heading: "", cta: { label: "Copiar e adaptar no editor", href: "/em-construcao" }},
    ],
  },
  {
    slug: "projetos-monitoria-extras-resultados-curriculo",
    title: "Projetos, monitoria e extras: transformando em resultados no currículo",
    excerpt: "Converta atividades acadêmicas em bullets com impacto e métricas.",
    cover: "/estagioai-background.png",
    tag: "Currículo",
    tags: ["Projetos", "Monitoria", "Resultados"],
    author: { name: "Equipe Estágio AI" },
    date: "2025-09-02",
    readingTimeMinutes: 7,
    sections: [
      { id: "introducao", heading: "Introdução", body: ["Atividades acadêmicas viram prova de resultado quando ligadas a métricas e impacto."]},
      { id: "entra", heading: "O que entra", list: ["Projetos de disciplina, iniciação científica, extensão.", "Monitoria, centro acadêmico, eventos organizados.", "Voluntariado e freelas."]},
      { id: "bullets", heading: "Como escrever bullets", body: ["Ação + ferramenta/método + métrica/impacto + contexto."], list: ["Criou dashboard de vendas (Sheets/Looker), reduzindo 2h/semana no fechamento."]},
      { id: "portfolio", heading: "Portfólio rápido", list: ["Repositório Git, pasta com PDFs, deck de 1 página por projeto."]},
      { id: "cta", heading: "", cta: { label: "Gerar bullets com métricas", href: "/em-construcao" }},
    ],
  },
  {
    slug: "onde-encontrar-vagas-estagio-como-filtrar",
    title: "Onde encontrar vagas de estágio e como filtrar",
    excerpt: "Canais, táticas e organização para candidaturas mais assertivas.",
    cover: "/company-login.png",
    tag: "Vagas",
    tags: ["Plataformas", "Filtros", "Alertas"],
    author: { name: "Equipe Estágio AI" },
    date: "2025-09-04",
    readingTimeMinutes: 6,
    sections: [
      { id: "introducao", heading: "Introdução", body: ["Encontrar vagas exige método de busca e triagem para eficiência e aderência."]},
      { id: "canais", heading: "Canais", list: ["Plataformas de estágio, LinkedIn Jobs, páginas de carreira.", "Portais da universidade, comunidades e grupos por área."]},
      { id: "taticas", heading: "Táticas de busca", list: ["Alertas por palavra‑chave + local + modalidade.", "Lista de empresas‑alvo e aplicações diretas.", "Filtros por período, idioma, softwares exigidos."]},
      { id: "organizacao", heading: "Organização", list: ["Planilha: link, status, prazo, feedback, follow‑up.", "Rotina de 30–45 min/dia para candidaturas personalizadas."]},
      { id: "cta", heading: "", cta: { label: "Baixar planilha de controle", href: "/em-construcao" }},
    ],
  },
  {
    slug: "o-que-perguntar-ao-entrevistador-no-final",
    title: "O que perguntar ao entrevistador no final",
    excerpt: "Perguntas finais que mostram preparo, curiosidade e fit com o time.",
    cover: "/logo-web.png",
    tag: "Entrevista",
    tags: ["Perguntas", "Fit", "Carreira"],
    author: { name: "Equipe Estágio AI" },
    date: "2025-09-06",
    readingTimeMinutes: 5,
    sections: [
      { id: "introducao", heading: "Introdução", body: ["Perguntas finais mostram preparo, curiosidade e fit com o time."]},
      { id: "impacto", heading: "Perguntas de impacto", list: [
        "Sucesso: Como medem o sucesso nos primeiros 90 dias?",
        "Rotina: Quais tarefas mais frequentes da função?",
        "Aprendizado: Quais ferramentas/processos terei treinamento?",
        "Time: Como é a interação com áreas parceiras?",
        "Próximos passos: Qual o cronograma e canais de contato?",
      ]},
      { id: "como-escolher", heading: "Como escolher", list: ["Priorize o que não foi respondido.", "Foque em entrega e aprendizado, não em benefícios."]},
      { id: "cta", heading: "", cta: { label: "Imprimir roteiro por área", href: "/em-construcao" }},
    ],
  },
  {
    slug: "como-adaptar-curriculo-e-carta-para-cada-vaga",
    title: "Como adaptar currículo e carta para cada vaga",
    excerpt: "Personalização por palavras‑chave e estrutura de carta em 3 parágrafos.",
    cover: "/logo-web copy.png",
    tag: "Currículo",
    tags: ["Carta", "Personalização", "Palavras‑chave"],
    author: { name: "Equipe Estágio AI" },
    date: "2025-09-09",
    readingTimeMinutes: 7,
    sections: [
      { id: "introducao", heading: "Introdução", body: ["Personalização aumenta compatibilidade com a descrição e acelera convites para entrevista."]},
      { id: "passo-a-passo", heading: "Passo a passo", list: ["Mapear palavras‑chave da vaga.", "Ajustar objetivo, habilidades e bullets com termos compatíveis.", "Trocar exemplos por casos da área/ferramentas pedidas."]},
      { id: "carta", heading: "Estrutura de carta", list: ["Abertura: função e onde viu a vaga.", "Meio: 2 conquistas relacionadas à descrição.", "Fecho: disponibilidade e agradecimento."]},
      { id: "cta", heading: "", cta: { label: "Usar personalizador de currículo e carta", href: "/em-construcao" }},
    ],
  },
  {
    slug: "entrevista-online-estagio-checklist-preparacao",
    title: "Entrevista online de estágio: checklist de preparação",
    excerpt: "Ambiente, som e linguagem corporal para entrevistas virtuais sem sustos.",
    cover: "/company-login.png",
    tag: "Entrevista",
    tags: ["Online", "Checklist", "Boas práticas"],
    author: { name: "Equipe Estágio AI" },
    date: "2025-09-12",
    readingTimeMinutes: 6,
    sections: [
      { id: "introducao", heading: "Introdução", body: ["Entrevistas virtuais exigem cuidado com ambiente, som e linguagem corporal."]},
      { id: "tecnico", heading: "Checklist técnico", list: ["Link testado, app atualizado, backup de internet.", "Câmera na altura dos olhos, fundo neutro, luz frontal.", "Microfone testado, fones à mão."]},
      { id: "conteudo", heading: "Checklist de conteúdo", list: ["PITCH de 60s, 3 cases STAR, 3 perguntas finais.", "Currículo e descrição da vaga à vista.", "Confirmação de horário e contato do recrutador."]},
      { id: "boas-praticas", heading: "Boas práticas", list: ["Entrar 5–10 minutos antes.", "Olhar para a câmera ao responder.", "Silenciar notificações, fechar abas e documentos."]},
      { id: "cta", heading: "", cta: { label: "Baixar checklist e roteiro de 60s", href: "/em-construcao" }},
    ],
  },
];

export function getPostBySlug(slug) {
  return posts.find((p) => p.slug === slug);
}
